### ISSUE TITLE
Default user account pythops has no sudo, can't login as root

### ISSUE THREAD

**Issue by baxks** [pythops/jetson-nano-image#16]
Hi I managed to generate the image thanks to your scripts, and after a lot of problems solved using solutions from the issues, I can login as (pythops, passwd pythops) but once trying sudo cmd, I get 
"sudo: /usr/bin/sudo must be owned by uid 0 and leave the setuid bit set"
also couldn't login as root or su into root or give it a passwd

I think i'm missing something or not understanding something so please explain how to get root account

**Comment by pythops** [comment]
That's strange 🤔 
Never encounter this problem before.
I would recommend to try again and create new image.
