### ISSUE TITLE
Fails to boot, stuck on splashscreen

### ISSUE THREAD

**Issue by SchynsO** [pythops/jetson-nano-image#19]
Hello,

I recently bought a Jetson nano 2G and I wanted to have a minimal OS so that I could install the packages I want.
I saw your tutorial and decided to give it a go.

I successfully built a image that I flashed on my SD card.
But then when I powerup the Jetson nano all I get is the Nvidia logo and I can't access any TTY.
I tried other images like the official Jetson SDK or the balena OS and they work fine.

My biggest concern is that I can't even see the logs during boot so that I could figure out, why the OS fail to start.
I don't know how to configure Ansible so that it would ditch the Nvidia logo and display the boot status.

**Comment by pythops** [comment]
Without any logs or messages it's gonna be difficult for me to help here. The root cause could be that the data was corrupted when flashing the sd card.
Try to flash again the sd card and if it does not work try again from the beginning and follow  the instructions step by step.
