### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by Urtetoli** [pythops/jetson-nano-image#22]
what changes to make to install Ubuntu version 18.04?

**Comment by Grungeby52** [comment]
> what changes to make to install Ubuntu version 18.04?

I was about to ask the exact same thing...

Best Regards

Onur Güzeldemirci

**Comment by pythops** [comment]
You need to change `create-rootfs.sh` and the ansible tasks. 
I'm gonna update the scripts this week to support that.

**Comment by Grungeby52** [comment]
Hi,

If I use this commit (Upgrade the ubuntu base image to 18.04.4) 

git checkout  a336c85d52dc580e42a77520bbed04228e63eca0

The image to be created is ubuntu 18.04 ?

Thanks for the quick reply

**Comment by pythops** [comment]
@Grungeby52  that wouldn't work. more changes are needed.

**Comment by pythops** [comment]
I made  decision to only support the latest stable version of Ubuntu.
