### ISSUE TITLE
OpenGL issue with Ubuntu Focal with BSP r32.5.1

### ISSUE THREAD

**Issue by pvmilk** [pythops/jetson-nano-image#35]
This is not an issue, maybe more like an inquiry. 

Has anyone successfully use OpenGL after the minimal installation?

I tried to use [VirtualGL](https://github.com/VirtualGL/virtualgl) + SSH-Forward with the headless setup, but failed to do so.
The error was more about the accessing the OpenGL API, so I was wondering whether could it be because the version of libGL.so is from mesa and it might not compatible with the Tegra. 

If anyone can use any OpenGL application on this minimal setup (maybe just glxinfo, or glxgears), what is the OpenGL package that is used (the mesa or something else)?

P.S. Please feel free to close the issue if it is unrelated to this repo, but the VirtualGL was working fine with the [nvidia image](jetson-nano-jp451-sd-card-image).

**Comment by pythops** [comment]
This inquiry is out of scope in my opinion. Unfortunately I can not help on this as I don't use any graphical app on my Jetson board.
