### ISSUE TITLE
Jetson not booting properly

### ISSUE THREAD

**Issue by sumanjha090** [pythops/jetson-nano-image#38]
I had followed your guide
1) created successfully jetson image (jetson.img).
2) When I tried flashing on micro sd card, I found your script is looking for mmcblk format storage chip and my micro sd is mounted as sda1 on my ubuntu 20.04 system. 
3) Then I commented the format check in your script(flash script) and successfully flashed image file on micro sd card.
**4) After that I inserted into Jetson 4GB nano board and tried to boot, it booted into terminal as root@localhost with error (ipv6 mld clamping qrv from 1 to 2) I didn't understood why.**

**I expected Jetson will boot with graphical interface. Please let me know if I am doing anything wrong.**

**Comment by pythops** [comment]
> When I tried flashing on micro sd card, I found your script is looking for mmcblk format storage chip and my micro sd is mounted as sda1 on my ubuntu 20.04 system.

In the section **Flash on the sdcard** there is this statement
:warning:  the sdcard path /dev/mmcblk0 may be different in your system.

> I expected Jetson will boot with graphical interface.

I never stated that

> Then I commented the format check in your script(flash script) and successfully flashed image file on micro sd card.4) After that I inserted into Jetson 4GB nano board and tried to boot, it booted into terminal as root@localhost with error (ipv6 mld clamping qrv from 1 to 2) I didn't understood why.

Once you boot your board, you should have tty, you enter your login and password (the default username is pythops and the password is pythops)  then you can get the terminal.
I don't understand this part where you say `it booted into terminal as root@localhost`
