### ISSUE TITLE
Network problems

### ISSUE THREAD

**Issue by mathiasn96** [pythops/jetson-nano-image#39]
Hi, I have followed the guide and created an Image.
My board is a Nano 4GB B01.

Mange to get tty access, but I'm struggling to get the Ethernet interface to work. There are no light activity when the cable is plugged in.

Do you have any advice?

Thank you in advance!

**Comment by pythops** [comment]
Try to identify the Ethernet interface with this command
```
$ ip a
```
Let's assume it's `eth0`, Then try to get an IP with this comman
```
$ sudo dhclient eth0
```
If it does not work, then check your router DHCP configuration
