### ISSUE TITLE
create-rootfs.sh: chroot failed to run command bin/bash exec format error

### ISSUE THREAD

**Issue by vcasadei** [pythops/jetson-nano-image#41]
Hi, I'm trying to use your project to create an image for my nano.

However, when I try to create the rootfs.sh I get the following message:

`$ sudo -E ./create-rootfs.sh
Install the dependencies...  [OK]
Create rootfs directory...    [OK]
Run debootstrap first stage...  [OK]
Run debootstrap second stage... chroot: failed to run command ‘/bin/bash’: Exec format error`

I'm running Linux on Windows, but that shouldn't be a problem, right?

Anyhow, my uname returns
`Linux DESKTOP-DKMB0C9 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

Do you have any idea what may be the problem?

Thanks

**Comment by pythops** [comment]
> I'm running Linux on Windows, but that shouldn't be a problem, right?

Well, seems to be.
I never used Linux on Windows. I would suggest that you create a linux virtual machine (ubuntu for instance) if you want to proceed with this repo.
