### ISSUE TITLE
Interesting project. Would it work for Jetson AGX?

### ISSUE THREAD

**Issue by charleswg** [pythops/jetson-nano-image#45]
Saw the blogpost and this repo. We have issues compiling trtexec for 7.1.3 and now forced to get TensorRT to version 8.

This github sheds some light on how to install a fresh Ubuntu 20.04 with cuda and tensorrt.

Anyone can share the experience for Jetson AGX?

Thanks.

**Comment by pythops** [comment]
To make it work with AGX, there are some changes you need to do but hey are not covered here as this is mainly for jetson nano boards
