### ISSUE TITLE
debootstrap hangs?

### ISSUE THREAD

**Issue by pilotnbr1** [pythops/jetson-nano-image#46]
At step "Run debootstrap first stage..."  nothing visibly happens. I have left it at this point for 12 hours and no change. 

Running this script on intel i5 x8 with up to date ubuntu 20.04

Any advice?

**Comment by pythops** [comment]
Not really, try again I would say.
Meanwhile take a look at your system if you have enough disk space, memory

**Comment by pilotnbr1** [comment]
Thanks for the response!

Trying it again but modified the script so it outputs to the terminal rather than null..

**Comment by pilotnbr1** [comment]
OK- success. Made sure to keep my computer awake and not interupt it. It took over 5 hours to create rootfs. Thanks for the support!
