### ISSUE TITLE
Boot from USB

### ISSUE THREAD

**Issue by fredlarochelle** [pythops/jetson-nano-image#50]
Hi!
Has anyone been able to only boot from USB without booting from the sd card first?

I have followed https://www.youtube.com/watch?v=53rRMr1IpWs, but even after changing the /boot/extlinux/extlinux.conf on both the SD card and the USB SSD, it won't boot when only the SSD is connected, but it is booting to the SSD when the SD card is plugged in.

I have even tried putting the image from Nvidia on the SD card and, same thing, the SD card need to be plugged in to boot to the SSD (with the custom image).

Also tried adding initramfs to the custom image, didn't work either, any ideas?

Thanks!

**Comment by pythops** [comment]
I'll close this issue as there was no update on it for a while
