### ISSUE TITLE
Jetson Linux R32.6.1 - update?

### ISSUE THREAD

**Issue by somera** [pythops/jetson-nano-image#51]
Hi,

will be there an update to Jetson Linux R32.6.1?

Thanks

**Comment by pythops** [comment]
Coming soon

**Comment by somera** [comment]
Sounds good. thx.

**Comment by pythops** [comment]
Next Monday

**Comment by somera** [comment]
@pythops nice. And Happy New Year!

**Comment by pythops** [comment]
Thanks
Happy new year :)

**Comment by pythops** [comment]
Enjoy :)

**Comment by somera** [comment]
Thx. I will take a look in some days.
