### ISSUE TITLE
unable to find directories after flashing the image into jetson nano

### ISSUE THREAD

**Issue by gyani73** [pythops/jetson-nano-image#58]
why does "ls" command show empty directories. it should show directories like home, etc, bin, etc.. right?
![WhatsApp Image 2022-03-10 at 23 09 06](https://user-images.githubusercontent.com/81769069/157727043-1d47ab03-61e7-44cb-a038-01a7a045fc9d.jpeg)

**Comment by pythops** [comment]
You're in the home directory of the user `pythops` `/home/pythops` and it's empty (not really cause you have some hidden files there).
I guess you need to improve your knowledge on Linux systems little bit
