### ISSUE TITLE
compatible pytorch wheel 

### ISSUE THREAD

**Issue by grassjelly** [pythops/jetson-nano-image#59]
Hi,  

Thanks for this very useful tool. Just want to ask if you happen to know any pre-built Pytorch wheel that's compatible with the Cuda libraries you've mentioned in your tutorial? Thank you!

**Comment by pythops** [comment]
Check this page:
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048

**Comment by grassjelly** [comment]
Thank you
