### ISSUE TITLE
How to flash on windows SD Card from Virtualbox 

### ISSUE THREAD

**Issue by eusoubrasileiro** [pythops/jetson-nano-image#61]
I managed to built the image on VirtualBox and Vagrant on Windows 10. 
I used Balena Etcher to flash to SD Card and it worked and Booted. 
But the disk is full to its maximum size 2GB. 

So I suppose I am doing something wrong in the flashing process. How to fix that? How to flash properly on Windows? 
Any suggestions are appreciated. 

I think I will try dd from mingw64.

**Comment by pythops** [comment]
I don' think that you're doing something wrong, probably the tools you're using to flash the SD card do not extend the filesystem in the image to take the whole space in your SD Card.
The `flash-sdcard.sh` script does that actually, but as you're using windows I don't know if it will work for you. However there is a solution that would work (That's something I will add soon) is a script to extend the filesystem when you boot the board to take the whole space.
