### ISSUE TITLE
Asking For Feedback: What packages you mostly need on top of the image and struggle installing ?

### ISSUE THREAD

**Issue by pythops** [pythops/jetson-nano-image#62]
Tell me about the packages you mostly need on top of the minimalist image but you struggle installing ? 
I'll pick up the most 3 common and I'll try to make tutorial on how to install them.

**Comment by eusoubrasileiro** [comment]
Just to give an update and feedback to future users. After much effort I finally managed to succeed in too fronts. :-)

- Based on [Sample RootFilesystem given by Nvidia.](https://developer.nvidia.com/embedded/linux-tegra-r3271) - [Here 1](https://github.com/eusoubrasileiro/jetson-nano-image/tree/bionic_nvidia_rootfs)
- Based on `BSP/Linux_for_Tegra/tools/samplefs` scripts - [Here 2](https://github.com/eusoubrasileiro/jetson-nano-image/tree/bionic_latest)
