### ISSUE TITLE
22.04

### ISSUE THREAD

**Issue by samuk** [pythops/jetson-nano-image#66]
Do you intend to update this for Ubuntu 22.04?

**Comment by pythops** [comment]
Yes, coming next week ;)

**Comment by pythops** [comment]
unfortunaly I need to cancel it cause a needed library by nvidia tools `libffi6` is only available in ubuntu 18.04, and I if I added the 18.04 repo in the 22.04 then I get some security issues.
Also, Nvidia does not support the jetson nano boards in their major update of jetpack 5.x 
So while waiting for Nvidia to support the boards, I'm gonna stick with ubuntu 20.04 for the moment
