### ISSUE TITLE
Question regarding "ubuntu_release"

### ISSUE THREAD

**Issue by hetfmt** [pythops/jetson-nano-image#67]
Hi,
In _"/ansible/roles/jetson/defaults/main.yaml"_ "ubuntu_release: focal" is defined.
In _"/ansible/roles/jetson/templates/etc/apt/sources.list"_, the following is defined:

> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }} main restricted
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-updates main restricted
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }} universe
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-updates universe
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }} multiverse
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-updates multiverse
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-backports main restricted universe multiverse
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-security main restricted
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-security universe
> deb http://ports.ubuntu.com/ubuntu-ports/ {{ ubuntu_release }}-security multiverse
> 
> '# Needed for libffi6
> deb http://ports.ubuntu.com/ubuntu-ports/ **bionic** main

On the last line, "bionic" is used instead of "{{ ubuntu_release }}" which is used on all the other lines. Is that intentional?

Thanks.

**Comment by pythops** [comment]
Hi,
Yes it is intentional. The reason is that one of the Nvidia libraries needed `libffi6` which is **only** available in the `bionic`  repositories.

**Comment by hetfmt** [comment]
Thank you :-)
