### ISSUE TITLE
Rootfs Error on Install the Dependencies

### ISSUE THREAD

**Issue by MrZahl** [pythops/jetson-nano-image#73]
![github](https://user-images.githubusercontent.com/112548662/187646134-7b2fdb37-8d83-46d6-98c6-869941d3f667.png)
Hello, can you help me with this problem? Is said that can't install because is not signed.

Thank you,

HrZahl.

**Comment by pythops** [comment]
You seems to have Debian operating system right ? You need to use a VM with ubuntu to processed. Check the `# Build environment (Optional)` section in the tutorial

**Comment by MrZahl** [comment]
![new](https://user-images.githubusercontent.com/112548662/187884378-660bb877-57fc-496f-96af-1604c0ee3ff5.png)
Hello, no, i'm using ubuntu...

**Comment by pythops** [comment]
check your `/etc/apt/sources.list`. Somehow you can not access a link (401 error)  in your config. You can comment it and run `$ sudo apt update`. 
Gonna close that one as it's not related to this repo but to your host config instead.
