### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by vkuehn** [pythops/jetson-nano-image#76]
Thanks for the project. 

The newes download version path looks like

https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jeston_nano/jetson-nano-jp461-sd-card-image.zip

but the path in create-image.sh is

https://developer.nvidia.com/embedded/l4t/r32_release_v7.2/t210/jetson-210_linux_r32.7.2_aarch64.tbz2

which looks newer. How  did you find the newer version and is it still valid ?

**Comment by pythops** [comment]
the first link is for the `jetpack`, the second link is for the BSP only.
if you follow the instructions in the blog post, you'll be able to build a working image yes
