### ISSUE TITLE
Cannot create rootfs

### ISSUE THREAD

**Issue by bui-thanh-lam** [pythops/jetson-nano-image#77]
![image](https://user-images.githubusercontent.com/47263060/200984393-adbf7520-ae72-4b0f-9938-643b48a7ca6e.png)
I've followed the instructions, but failed on the first step (image above).
My host OS: Ubuntu 20.04.
Is the script still OK, or it needs updating?

Thanks

**Comment by pythops** [comment]
this seems to be more related to your OS than the script
try to run:
```
$ sudo apt-get update
```
what do you get ?
if it works, try to run the script again
