### ISSUE TITLE
Out of the box image creation for B02 gives error

### ISSUE THREAD

**Issue by crazybert** [pythops/jetson-nano-image#78]
tar: Exiting with failure status due to previous errors
Failed. Your APPSIZE might be too small.

Ubuntu 22.02, fresh setup, no customization

**Comment by crazybert** [comment]
Figured out.
Build host was using zfs with compression enabled, and apparently it was saving more than 10% that are added for margin of error.

**Comment by pythops** [comment]
glad that you figured it out :+1:  :)
