### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by snppla** [pythops/jetson-nano-image#80]
I'm just starting to play around with these scripts. It seems trivial to add support for Ubuntu 22.04. If you aren't aware of a reason it wouldn't be, I'll spend a little time modifying the scripts to support 22.04 and make a pull request (mostly seems there but I found a couple spots that it wouldn't work).

**Comment by pythops** [comment]
I tried already but  I run into many issues when trying to install nvidia libraries. 
for the moment I think it's best to stick with ubuntu 20.04 untill Nvidia releases jetpack 5.x for jetson nano then I'll upgrade.
