### ISSUE TITLE
I can't use sudo.

### ISSUE THREAD

**Issue by bdh1993** [pythops/jetson-nano-image#86]
I got the updated contents today and build it.
It works well.
Thank you .

I confirmed that the login ID,PW is jetson.
But there seems to be a problem with using sudo.

**sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set**

It cannot be modified because sudo cannot be used.

Is there a way to access the root account?

**Comment by pythops** [comment]
a fix is coming

**Comment by pythops** [comment]
fixed

**Comment by bdh1993** [comment]
Thank you
