### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by debloper** [pythops/jetson-nano-image#96]
So, I've been able to update the installation (distro upgrade) to 22.04 (please excuse the poor/low-light quality); so it's possible to run it.

![photo_2023-05-12](https://github.com/pythops/jetson-nano-image/assets/536060/0ff801d8-f3fc-41bc-bd2a-fd0ea89ce962)

Just wondering if there's any docs on why we couldn't build the image around it. What are the errors, and if we can keep this issue as a paper trail of how we're approaching to fix them.

I'll give it a try in my fork, and document the findings here. Meanwhile, if anyone else is trying, please also share your findings here.

**Comment by pythops** [comment]
GJ :clap: 
I had some issues with nvidia libraries and I've just gave up. 
on the jetson orin nano I'm working on, it will be based on 22.04

**Comment by mrcmunir** [comment]
Hi for nvidia blobs gpu libs working you needed apt hold xorg server package stuck down to 1.20 version.

Seems xorg 1.21 broken ABI compatibility due changes in https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/468

Drivers with old structure always broken due randr variable are different.
@pythops

**Comment by debloper** [comment]
Was able to optimize the boot down to 4 seconds, and total installed storage size below 2GB ([ref](https://github.com/debloper/jetson-nano-image/releases/tag/32.7.3)). I was trying for sub-10sec boot, but got carried away, and for the image size, smaller is better, right!

I've also enabled the [remaining 2 hidden cores](https://forums.developer.nvidia.com/t/two-cores-disabled/48637/21), for a hexacore powerhouse (well, for a ~4yo SBC anyway).

Just posting this as a reference for what seems possible, for anyone continuing the work.

> ☣️ Now personally, I really want to create a spin-off aftermarket distro image for Jetson Nano that's heavily focused on latest software and extreme performance (by slicing down everything that can get in its way). I taste blood in the water lol!

**Comment by pythops** [comment]
Done here #104
